name: Product Management Links
description: "Essential resources for Product Managers"
meta_description: "Essential resources for Product Managers"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
excerpt_separator: <!--more-->
baseurl: '/pmlinks/'

# Details for the RSS feed generator
url:            'http://www.lokimeyburg.com/pmlinks/'
author:         'Loki Meyburg'

gems: ['jekyll-paginate']

collections:
  sections:
    output: true
    permalink: /section/:path/
